# 10 Statistical Tests

## 10-1 Configuration

In [ ]:
!rm -rf /content/unet-ensemble

In [2]:
!git clone https://github.com/JeserylMae/unet-ensemble.git

fatal: destination path 'unet-ensemble' already exists and is not an empty directory.

In [3]:
from google.colab import drive
import sys

drive.mount('/content/drive')
sys.path.append('/content/unet-ensemble')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [4]:
import warnings
import pandas as pd
from src.eval.tests import Test

warnings.filterwarnings('ignore')

In [5]:
test = Test()

CSV_ROOT_DIR = '/content/drive/Shareddrives/U-Net Ensemble/Files/Evaluation'
OUTPUT_SAVE_DIR = '/content/drive/Shareddrives/U-Net Ensemble/Files/Evaluation/results'

## 10-3 Comparative Assumptions Against Baseline Models

#### A. Data Preparation

In [6]:
OUTPUT_FILE_NAME = 'ensemble-vs-baselines.csv'

DIFF_ID_PATH     = f'{CSV_ROOT_DIR}/csv/diff-id_iou_dice_bf-score.csv'
TWO_STREAM_PATH  = f'{CSV_ROOT_DIR}/csv/two-stream-cnn_iou_dice_bf-score.csv'
XCEPTIONNET_PATH = f'{CSV_ROOT_DIR}/csv/xceptionnet_iou_dice_bf-score.csv'
SEGFORMER_PATH   = f'{CSV_ROOT_DIR}/csv/segformer_iou_dice_bf-score.csv' 

diff_id_df      = pd.read_csv(DIFF_ID_PATH)
two_stream_df   = pd.read_csv(TWO_STREAM_PATH)
xceptionnet_df  = pd.read_csv(XCEPTIONNET_PATH)
segformer_df    = pd.read_csv(SEGFORMER_PATH)

BASELINES = {
    'Diff-ID': {
        'df'      : diff_id_df,
        'iou'     : 'diff_iou',
        'bf_score': 'diff_bf_score',
    },
    'Two-Stream CNN': {
        'df'      : two_stream_df,
        'iou'     : 'diff_iou',
        'bf_score': 'diff_bf_score',
    },
    'XceptionNet': {
        'df'      : xceptionnet_df,
        'iou'     : 'diff_iou',
        'bf_score': 'diff_bf_score',
    },
    'SegFormer': {
        'df'      : segformer_df,
        'iou'     : 'diff_iou',
        'bf_score': 'diff_bf_score',
    },
}

#### B. Perform Testing

In [7]:
summary_10_2 = test.run_tests(
    groups    = BASELINES,
    metrics   = [
        ('IoU',      'iou'),
        ('BF Score', 'bf_score'),
    ],
    tests     = ['shapiro', 'wilcoxon', 'ci'],
    group_col = 'Baseline',
)
summary_10_2

,Metric,Baseline,Mean Diff,SW p,Normal,W p,Significant W p,CI Lower,CI Upper,CI Level,Favors Proposed
0,IoU,Diff-ID,0.029185,1.3773e-51,False,1.000000e+00,False,0.017729,0.041669,95.0%,True
1,BF Score,Diff-ID,0.026565,1.0954e-50,False,9.800420e-01,False,0.015042,0.039075,95.0%,True
2,IoU,Two-Stream CNN,0.040032,8.1418e-51,False,1.000000e+00,False,0.027633,0.053400,95.0%,True
3,BF Score,Two-Stream CNN,0.038167,5.1386e-50,False,2.807902e-01,False,0.025296,0.051849,95.0%,True
4,IoU,XceptionNet,0.011362,1.0201e-42,False,2.304385e-41,True,0.009056,0.013618,95.0%,True
5,BF Score,XceptionNet,0.026074,1.2408e-43,False,1.408136e-20,True,0.020350,0.032190,95.0%,True
6,IoU,SegFormer,0.033518,5.6096e-51,False,1.000000e+00,False,0.021909,0.046038,95.0%,True
7,BF Score,SegFormer,0.033809,5.3858e-50,False,6.288887e-01,False,0.021595,0.047006,95.0%,True

#### C. Save Results

In [21]:
summary_10_2.to_csv(f'{OUTPUT_SAVE_DIR}/{OUTPUT_FILE_NAME}', index=False)
print('Saved.')

Saved.

## 10-4 Dual-Feature vs. All-Three-Feature Assumptions

### Metric Difference Comparison
It compares:
1. ALL vs P+L
2. ALL vs P+F
3. ALL vs F+L

#### A. Data Preparation

In [10]:
OUTPUT_FILE_NAME = 'dual-feature-vs-three-feature_wilcoxon.csv'

UNETPP_PATH = f'{CSV_ROOT_DIR}/csv/unetpp_iou_bf-score.csv'
ENSEMBLE_PATH = f'{CSV_ROOT_DIR}/csv/unet-ensemble_iou_bf-score.csv'
ATTENUNET_PATH = f'{CSV_ROOT_DIR}/csv/attention-unet_iou_bf-score.csv'

unetpp_df = pd.read_csv(UNETPP_PATH)
ensemble_df = pd.read_csv(ENSEMBLE_PATH)
attenunet_df = pd.read_csv(ATTENUNET_PATH)

MODELS = {
    'U-Net++ IoU': {
        'df': unetpp_df,
        'prnu_illum_iou': 'diff_prnu_illum_iou',
        'prnu_freq_iou': 'diff_prnu_freq_iou',
        'freq_illum_iou': 'diff_freq_illum_iou',
        'prnu_illum_bfs': 'diff_prnu_illum_bfs',
        'prnu_freq_bfs': 'diff_prnu_freq_bfs',
        'freq_illum_bfs': 'diff_freq_illum_bfs',
    },
    'U-Net Ensemble IoU':{
        'df': ensemble_df,
        'prnu_illum_iou': 'diff_prnu_illum_iou',
        'prnu_freq_iou': 'diff_prnu_freq_iou',
        'freq_illum_iou': 'diff_freq_illum_iou',
        'prnu_illum_bfs': 'diff_prnu_illum_bfs',
        'prnu_freq_bfs': 'diff_prnu_freq_bfs',
        'freq_illum_bfs': 'diff_freq_illum_bfs',
    },
    'Attention U-Net IoU': {
        'df': attenunet_df,
        'prnu_illum_iou': 'diff_prnu_illum_iou',
        'prnu_freq_iou': 'diff_prnu_freq_iou',
        'freq_illum_iou': 'diff_freq_illum_iou',
        'prnu_illum_bfs': 'diff_prnu_illum_bfs',
        'prnu_freq_bfs': 'diff_prnu_freq_bfs',
        'freq_illum_bfs': 'diff_freq_illum_bfs',
    },
}

#### B. Perform Testing

In [11]:
summary_10_3 = test.run_tests(
    groups    = MODELS,
    metrics   = [
        ('PRNU + Illumination IoU',      'prnu_illum_iou'),
        ('PRNU + Frequency IoU',         'prnu_freq_iou'),
        ('Frequency + Illumination IoU', 'freq_illum_iou'),
        ('PRNU + Illumination BFS',      'prnu_illum_bfs'),
        ('PRNU + Frequency BFS',         'prnu_freq_bfs'),
        ('Frequency + Illumination BFS', 'freq_illum_bfs'),
    ],
    tests     = ['shapiro', 'wilcoxon'],
    group_col = 'Model',
)
summary_10_3

,Metric,Model,Mean Diff,SW p,Normal,W p,Significant W p
0,PRNU + Illumination IoU,U-Net++ IoU,0.002990,2.3908e-54,False,5.215027e-01,False
1,PRNU + Frequency IoU,U-Net++ IoU,0.001685,5.0933e-54,False,8.223128e-02,False
2,Frequency + Illumination IoU,U-Net++ IoU,0.008523,9.4755e-49,False,3.858226e-31,True
3,PRNU + Illumination BFS,U-Net++ IoU,0.003064,3.9119e-51,False,4.873018e-01,False
4,PRNU + Frequency BFS,U-Net++ IoU,0.004108,6.7219e-50,False,2.814426e-02,True
5,Frequency + Illumination BFS,U-Net++ IoU,0.018419,2.0096e-43,False,8.213548e-13,True
6,PRNU + Illumination IoU,U-Net Ensemble IoU,-0.000834,1.0773e-37,False,9.787954e-01,False
7,PRNU + Frequency IoU,U-Net Ensemble IoU,0.000714,1.3876e-53,False,7.725988e-01,False
8,Frequency + Illumination IoU,U-Net Ensemble IoU,0.008117,1.4924e-43,False,4.064608e-30,True
9,PRNU + Illumination BFS,U-Net Ensemble IoU,-0.000788,3.4064e-45,False,7.964469e-01,False
10,PRNU + Frequency BFS,U-Net Ensemble IoU,0.002320,8.0583e-49,False,2.098231e-01,False
11,Frequency + Illumination BFS,U-Net Ensemble IoU,0.017776,1.8422e-43,False,2.925392e-12,True
12,PRNU + Illumination IoU,Attention U-Net IoU,-0.001245,5.0247e-33,False,9.940460e-01,False
13,PRNU + Frequency IoU,Attention U-Net IoU,-0.000312,2.4398e-52,False,9.980653e-01,False
14,Frequency + Illumination IoU,Attention U-Net IoU,0.008221,1.2750e-46,False,1.235866e-26,True
15,PRNU + Illumination BFS,Attention U-Net IoU,-0.002086,2.8952e-43,False,9.673007e-01,False
16,PRNU + Frequency BFS,Attention U-Net IoU,0.000363,2.0872e-46,False,8.126187e-01,False
17,Frequency + Illumination BFS,Attention U-Net IoU,0.021771,5.6194e-43,False,1.625959e-13,True

#### C. Save Results

In [12]:
summary_10_3.to_csv(f'{OUTPUT_SAVE_DIR}/{OUTPUT_FILE_NAME}', index=False)
print('Saved.')

Saved.

### Kruskal-Wallis Test

#### A. Data Preparation

In [13]:
OUTPUT_FILE_NAME = 'dual-feature-vs-three-feature_kruskal.csv'

UNETPP_PATH = f'{CSV_ROOT_DIR}/csv/unetpp_iou_bf-score.csv'
ENSEMBLE_PATH = f'{CSV_ROOT_DIR}/csv/unet-ensemble_iou_bf-score.csv'
ATTENUNET_PATH = f'{CSV_ROOT_DIR}/csv/attention-unet_iou_bf-score.csv'

unetpp_df = pd.read_csv(UNETPP_PATH)
ensemble_df = pd.read_csv(ENSEMBLE_PATH)
attenunet_df = pd.read_csv(ATTENUNET_PATH)

MODELS = {
    'U-Net++ (P+L)': {
        'df': unetpp_df,
        'iou': 'unetpp_prnu_illum_iou',
        'bfs': 'unetpp_prnu_illum_bfs',
        'kruskal_groups': {
            'iou': [ 'unetpp_all_iou', ],
            'bfs': [ 'unetpp_all_bfs', ]
        }
    },
    'U-Net++ (P+F)': {
        'df': unetpp_df,
        'iou': 'unetpp_prnu_freq_iou',
        'bfs': 'unetpp_prnu_freq_bfs',
        'kruskal_groups': {
            'iou': [ 'unetpp_all_iou', ],
            'bfs': [ 'unetpp_all_bfs', ]
        }
    }, 
    'U-Net++ (F+L)': {
        'df': unetpp_df,
        'iou': 'unetpp_freq_illum_iou',
        'bfs': 'unetpp_freq_illum_bfs',
        'kruskal_groups': {
            'iou': [ 'unetpp_all_iou', ],
            'bfs': [ 'unetpp_all_bfs', ]
        }
    },

    'U-Net Ensemble (P+L)': {
        'df': ensemble_df,
        'iou': 'ensemble_prnu_illum_iou',
        'bfs': 'ensemble_prnu_illum_bfs',
        'kruskal_groups': {
            'iou': [ 'ensemble_all_iou' ],
            'bfs': [ 'ensemble_all_bfs' ]
        }
    },
    'U-Net Ensemble (P+F)': {
        'df': ensemble_df,
        'iou': 'ensemble_prnu_freq_iou',
        'bfs': 'ensemble_prnu_freq_bfs',
        'kruskal_groups': {
            'iou': [ 'ensemble_all_iou' ],
            'bfs': [ 'ensemble_all_bfs' ]
        }
    },
    'U-Net Ensemble (F+L)': {
        'df': ensemble_df,
        'iou': 'ensemble_freq_illum_iou',
        'bfs': 'ensemble_freq_illum_bfs',
        'kruskal_groups': {
            'iou': [ 'ensemble_all_iou' ],
            'bfs': [ 'ensemble_all_bfs' ]
        }
    },

    'Attention U-Net (P+L)': {
        'df': attenunet_df,
        'iou': 'attenunet_prnu_illum_iou',
        'bfs': 'attenunet_prnu_illum_bfs',
        'kruskal_groups': {
            'iou': [ 'attenunet_all_iou' ],
            'bfs': [ 'attenunet_all_bfs' ]
        }
    }, 
    'Attention U-Net (P+F)': {
        'df': attenunet_df,
        'iou': 'attenunet_prnu_freq_iou',
        'bfs': 'attenunet_prnu_freq_bfs',
        'kruskal_groups': {
            'iou': [ 'attenunet_all_iou' ],
            'bfs': [ 'attenunet_all_bfs' ]
        }
    },
    'Attention U-Net (F+L)': {
        'df': attenunet_df,
        'iou': 'attenunet_freq_illum_iou',
        'bfs': 'attenunet_freq_illum_bfs',
        'kruskal_groups': {
            'iou': [ 'attenunet_all_iou' ],
            'bfs': [ 'attenunet_all_bfs' ]
        }
    },
}

#### B. Perform Testing

In [14]:
summary_10_4 = test.run_tests(
    groups    = MODELS,
    metrics   = [
        ('IoU', 'iou'),
        ('BF Score', 'bfs')
    ],
    tests     = ['shapiro', 'kruskal'],
    group_col = 'Model',
)
summary_10_4

,Metric,Model,Mean Diff,SW p,Normal,Kruskal p,Significant Kruskal p
0,IoU,U-Net++ (P+L),0.965028,1.4830e-50,False,8.6571e-01,False
1,BF Score,U-Net++ (P+L),0.973882,1.3572e-51,False,5.8802e-01,False
2,IoU,U-Net++ (P+F),0.966332,1.7691e-49,False,7.2251e-01,False
3,BF Score,U-Net++ (P+F),0.972838,1.4749e-50,False,1.1648e-01,False
4,IoU,U-Net++ (F+L),0.959495,4.9978e-44,False,3.0313e-04,True
5,BF Score,U-Net++ (F+L),0.958527,7.8030e-47,False,1.7365e-06,True
6,IoU,U-Net Ensemble (P+L),0.970482,4.1511e-48,False,7.6294e-01,False
7,BF Score,U-Net Ensemble (P+L),0.980552,6.2517e-52,False,3.9174e-01,False
8,IoU,U-Net Ensemble (P+F),0.968934,3.3766e-49,False,9.6838e-01,False
9,BF Score,U-Net Ensemble (P+F),0.977444,1.6835e-51,False,6.3932e-01,False
10,IoU,U-Net Ensemble (F+L),0.961532,8.7723e-42,False,5.9494e-04,True
11,BF Score,U-Net Ensemble (F+L),0.961988,6.9632e-48,False,2.9643e-06,True
12,IoU,Attention U-Net (P+L),0.967752,6.8868e-49,False,6.3406e-01,False
13,BF Score,Attention U-Net (P+L),0.977547,3.4297e-51,False,1.6981e-01,False
14,IoU,Attention U-Net (P+F),0.966820,2.1392e-49,False,6.3843e-01,False
15,BF Score,Attention U-Net (P+F),0.975098,4.6020e-51,False,5.6952e-01,False
16,IoU,Attention U-Net (F+L),0.958287,1.2548e-40,False,9.8769e-04,True
17,BF Score,Attention U-Net (F+L),0.953690,8.8047e-47,False,6.8684e-06,True

#### C. Save Results

In [15]:
summary_10_4.to_csv(f'{OUTPUT_SAVE_DIR}/{OUTPUT_FILE_NAME}', index=False)
print('Saved.')

Saved.

## 10-5 Ensemble Mask Fusion Assumptions

#### A. Data Preparation

In [17]:
OUTPUT_FILE_NAME = 'ensemble-vs-single-model.csv'


UNETPP_PATH = f'{CSV_ROOT_DIR}/csv/unetpp_iou_bf-score.csv'
ENSEMBLE_PATH = f'{CSV_ROOT_DIR}/csv/unet-ensemble_iou_bf-score.csv'
ATTENUNET_PATH = f'{CSV_ROOT_DIR}/csv/attention-unet_iou_bf-score.csv'

unetpp_df = pd.read_csv(UNETPP_PATH)
ensemble_df = pd.read_csv(ENSEMBLE_PATH)
attenunet_df = pd.read_csv(ATTENUNET_PATH)

df = pd.DataFrame() 
df['diff_ensemble_unetpp_iou']      = ensemble_df['ensemble_all_iou'] - unetpp_df['unetpp_all_iou']
df['diff_ensemble_unetpp_bfs'] = ensemble_df['ensemble_all_bfs'] - unetpp_df['unetpp_all_bfs']

df['diff_ensemble_attenunet_iou']      = ensemble_df['ensemble_all_iou'] - attenunet_df['attenunet_all_iou']
df['diff_ensemble_attenunet_bfs'] = ensemble_df['ensemble_all_bfs'] - attenunet_df['attenunet_all_bfs']

MODELS = {
    'U-Net++': {
        'df'      : df,
        'iou'     : 'diff_ensemble_unetpp_iou',
        'bf_score': 'diff_ensemble_unetpp_bfs',
    },
    'Attention U-Net': {
        'df'      : df,
        'iou'     : 'diff_ensemble_attenunet_iou',
        'bf_score': 'diff_ensemble_attenunet_bfs',
    },
}

#### B. Perform Testing

In [18]:
summary_10_7 = test.run_tests(
    groups      = MODELS,
    metrics     = [
        ('IoU', 'iou'),
        ('BF Score', 'bf_score'),
    ],
    tests       = ['shapiro', 'wilcoxon', 'ci'],
    group_col   = 'Model'
)
summary_10_7

,Metric,Model,Mean Diff,SW p,Normal,W p,Significant W p,CI Lower,CI Upper,CI Level,Favors Proposed
0,IoU,U-Net++,0.001631,4.5807e-55,False,2.502528e-04,True,0.000205,0.004040,95.0%,True
1,BF Score,U-Net++,0.002818,4.5358e-52,False,1.614423e-03,True,0.000589,0.005577,95.0%,True
2,IoU,Attention U-Net,0.003141,6.1661e-52,False,1.823113e-28,True,0.002297,0.004339,95.0%,True
3,BF Score,Attention U-Net,0.004303,1.3723e-45,False,2.353001e-09,True,0.002677,0.005943,95.0%,True

#### C. Save Results

In [19]:
summary_10_7.to_csv(f'{OUTPUT_SAVE_DIR}/{OUTPUT_FILE_NAME}', index=False)
print('Saved.')

Saved.